import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import api from '../api/axios';

export default function Login() {
  const { login } = useAuth();
  const navigate = useNavigate();
  const [form, setForm] = useState({ email: '', password: '' });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(''); setLoading(true);
    try {
      const res = await api.post('/auth/login', form);
      login(res.data.token, res.data.user);
      navigate('/dashboard');
    } catch (err: any) {
      setError(err.response?.data?.message || 'Login failed.');
    } finally { setLoading(false); }
  };

  return (
    <div className="auth-page">
      <div className="auth-left">
        <div className="auth-hero-text">
          <div className="auth-brand" style={{ marginBottom: '2rem' }}>
            <div className="auth-brand-icon">S</div>
            <div className="auth-brand-name">StudyAI</div>
          </div>
          <h1>Your AI-powered<br />study companion<br /><span>for exam success.</span></h1>
          <p style={{ marginTop: '1rem' }}>Upload your syllabus. Get instant notes, questions, MCQs, and tests generated by Gemini AI.</p>
          <div className="auth-features">
            {['Auto-extract topics from any PDF syllabus','Generate structured notes per topic','Practice with MCQs & viva questions','Take AI-generated unit-wise tests','Track your progress & performance'].map(f => (
              <div key={f} className="auth-feature">
                <div className="auth-feature-dot" />
                {f}
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="auth-right">
        <div className="auth-card">
          <div className="auth-brand">
            <div className="auth-brand-icon">S</div>
            <div className="auth-brand-name">StudyAI</div>
          </div>
          <h2 className="auth-title">Welcome back</h2>
          <p className="auth-desc">Sign in to continue your learning journey</p>

          {error && <div className="alert alert-error">{error}</div>}

          <form onSubmit={submit}>
            <div className="form-group">
              <label className="form-label">Email</label>
              <input className="form-input" type="email" placeholder="you@example.com" value={form.email} onChange={e => setForm({...form, email: e.target.value})} required />
            </div>
            <div className="form-group">
              <label className="form-label">Password</label>
              <input className="form-input" type="password" placeholder="••••••••" value={form.password} onChange={e => setForm({...form, password: e.target.value})} required />
            </div>
            <button className="btn btn-primary btn-full btn-lg" style={{ marginTop: '0.5rem' }} disabled={loading}>
              {loading ? 'Signing in...' : 'Sign In →'}
            </button>
          </form>

          <p className="auth-switch">No account? <Link to="/register">Create one free</Link></p>
        </div>
      </div>
    </div>
  );
}